[versions]
# Library Versions
kdto-annotations = "1.0.1"
kdto-processor = "1.0.3"
kdto-plugin = "1.0.3"

# Dependencies Versions
kotlin = "2.2.21"
kotlin-poet = "2.2.0"
kotlin-compile-testing = "1.6.0"
ksp = "2.3.3"
jreleaser = "1.17.0"
gradle-publish = "1.2.1"

[libraries]
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref  = "kotlin" }
ksp-symbol-processor = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlin-compile-testing = { module = "com.github.tschuchortdev:kotlin-compile-testing", version.ref = "kotlin-compile-testing" }
kotlin-compile-testing-ksp = { module = "com.github.tschuchortdev:kotlin-compile-testing-ksp", version.ref = "kotlin-compile-testing" }
kotlin-poet = { module = "com.squareup:kotlinpoet", version.ref = "kotlin-poet" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
gradle-plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "gradle-publish" }